#ifndef SYNTAXPARSE_GLOBAL_H
#define SYNTAXPARSE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYNTAXPARSE_LIBRARY)
#  define SYNTAXPARSESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYNTAXPARSESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYNTAXPARSE_GLOBAL_H
